const js = require('@eslint/js');
const globals = require('globals');
const stylistic = require('@stylistic/eslint-plugin');
const importX = require('eslint-plugin-import-x');
const comments = require('@eslint-community/eslint-plugin-eslint-comments');

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      globals: {
        ...globals.node,
      },
    },
    plugins: {
      '@stylistic': stylistic,
      'import-x': importX,
      '@eslint-community/eslint-comments': comments,
    },
    rules: {
      // eslint-base (logic / correctness / conventions)
      'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: true }],
      'camelcase': 'error',
      'class-methods-use-this': 'off',
      'complexity': ['error', { max: 10 }],
      'constructor-super': 'error',
      'curly': ['error', 'all'],
      'default-case': 'error',
      'default-case-last': 'error',
      'dot-notation': 'error',
      'eqeqeq': ['error', 'always'],
      'func-style': ['error', 'declaration'],
      'guard-for-in': 'off',
      // Renamed from the deprecated `id-blacklist`.
      'id-denylist': [
        'error',
        'any',
        'Number',
        'number',
        'String',
        'string',
        'Boolean',
        'boolean',
        'Undefined',
        'undefined',
      ],
      'id-match': 'error',
      'max-classes-per-file': ['error', 1],
      'max-lines': 'off',
      'new-cap': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-cond-assign': 'error',
      'no-console': 'off',
      'no-debugger': 'error',
      'no-empty': 'error',
      'no-eval': 'error',
      'no-fallthrough': 'error',
      'no-invalid-this': 'off',
      'no-irregular-whitespace': 'error',
      'no-magic-numbers': 'off',
      'no-nested-ternary': 'error',
      'no-new-wrappers': 'error',
      'no-redeclare': 'error',
      'no-shadow': 'off',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'off',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unused-expressions': 'error',
      'no-unused-labels': 'error',
      'no-unused-vars': 'error',
      'no-use-before-define': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'object-shorthand': 'error',
      'one-var': ['error', 'never'],
      'prefer-const': 'error',
      'prefer-object-spread': 'error',
      'prefer-template': 'off',
      'radix': 'off',
      'use-isnan': 'error',
      'valid-typeof': 'off',
      'yoda': 'error',

      // eslint-base (new rules, matched to the existing strict philosophy)
      'array-callback-return': 'error',
      'no-constructor-return': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-object-constructor': 'error',
      'no-promise-executor-return': 'error',
      'no-self-compare': 'error',
      'no-unassigned-vars': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable-loop': 'error',
      'no-useless-assignment': 'error',
      'prefer-object-has-own': 'error',
      'preserve-caught-error': 'error',

      // @stylistic (formatting; migrated from deprecated eslint core rules)
      '@stylistic/arrow-parens': 'off',
      '@stylistic/brace-style': ['error', 'stroustrup', { allowSingleLine: true }],
      '@stylistic/comma-dangle': ['error', 'always-multiline'],
      '@stylistic/comma-spacing': ['error', { before: false, after: true }],
      '@stylistic/comma-style': ['error', 'last'],
      '@stylistic/eol-last': 'error',
      '@stylistic/indent': ['error', 2, { SwitchCase: 1 }],
      '@stylistic/key-spacing': [1, { beforeColon: false, afterColon: true, mode: 'minimum' }],
      '@stylistic/keyword-spacing': ['error', { after: true }],
      '@stylistic/linebreak-style': ['error', 'unix'],
      '@stylistic/lines-between-class-members': ['error', 'always'],
      '@stylistic/max-len': ['error', { code: 140 }],
      '@stylistic/new-parens': 'error',
      '@stylistic/no-floating-decimal': 'error',
      '@stylistic/no-mixed-operators': 'error',
      '@stylistic/no-trailing-spaces': 'error',
      '@stylistic/operator-linebreak': ['error', 'before', { overrides: { '+': 'after' } }],
      '@stylistic/padding-line-between-statements': 'off',
      '@stylistic/quote-props': 'off',
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      '@stylistic/space-before-blocks': 'error',
      '@stylistic/space-before-function-paren': ['error', {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
      }],
      '@stylistic/space-in-parens': ['error', 'never'],
      '@stylistic/spaced-comment': 'error',
      '@stylistic/wrap-iife': 'error',

      // eslint-plugin-import-x
      'import-x/first': 'error',
      'import-x/newline-after-import': 'error',
      'import-x/no-absolute-path': 'error',
      'import-x/no-amd': 'error',
      'import-x/no-default-export': 'error',
      'import-x/no-extraneous-dependencies': ['error', {
        devDependencies: true,
        peerDependencies: true,
        optionalDependencies: false,
      }],
      'import-x/no-mutable-exports': 'error',
      'import-x/no-named-default': 'error',
      'import-x/no-named-export': 'off', // we want everything to be a named export
      'import-x/no-self-import': 'error',
      'import-x/no-unassigned-import': 'off',
      'import-x/order': 'off',
      'import-x/prefer-default-export': 'off', // we want everything to be named

      // @eslint-community/eslint-comments (maintained successor to eslint-plugin-eslint-comments)
      '@eslint-community/eslint-comments/disable-enable-pair': ['error', {
        allowWholeFile: true,
      }],
      '@eslint-community/eslint-comments/no-aggregating-enable': 'error',
      '@eslint-community/eslint-comments/no-duplicate-disable': 'error',
      '@eslint-community/eslint-comments/no-unlimited-disable': 'error',
      '@eslint-community/eslint-comments/no-unused-disable': 'error',
      '@eslint-community/eslint-comments/no-unused-enable': 'error',
      '@eslint-community/eslint-comments/no-use': ['error', {
        allow: [
          'eslint-disable',
          'eslint-disable-line',
          'eslint-disable-next-line',
          'eslint-enable',
        ],
      }],
    },
  },
];
